articles/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from .views import *

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^article/(?P<id>\d+)$', detail, name='detail'),
    url(r'^create$', create, name='create'),
    url(r'^update/(?P<id>\d+)$', update, name='update'),
    url(r'^delete/(?P<id>\d+)$', delete, name='delete'),
]

blog/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('articles.urls', namespace='articles')),
    url(r'^users/', include('users.urls', namespace='users'))
]


if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from .views import *

urlpatterns = [
    url(r'^login$', login, name='login'),
    url(r'^register$', register, name='register'),
    url(r'^logout$', logout, name='logout'),
]

articles/models.py
from __future__ import unicode_literals

from users.models import User
from django.db import models

# Create your models here.
class Article(models.Model):
    user = models.ForeignKey(User)

    title = models.CharField(max_length=120)
    content = models.TextField(blank=True)

    image = models.ImageField(upload_to='images/')

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        get_latest_by = 'created'

    def __str__(self):
        return self.title

users/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.
class User(AbstractUser):
    profile_image = models.ImageField(upload_to='users/', default='users/profile_image.png',blank=True)

    def __str__(self):
        return self.username

articles/forms.py
from django import forms

from .models import Article


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ('title', 'content', 'image')

users/forms.py
from django import forms

from .models import User


class LoginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'password')
        widgets = {
            'password': forms.TextInput(attrs={'type': 'password'}),
        }


class RegisterForm(forms.ModelForm):
    confirmed_password = forms.CharField()

    class Meta:
        model = User
        fields = ('username', 'email', 'password', 'confirmed_password')
        widgets = {
            'password': forms.TextInput(attrs={'type': 'password'}),
            'confirmed_password': forms.TextInput(attrs={'type': 'password'}),
        }

articles/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages

from .forms import ArticleForm
from .models import Article


# Create your views here.
def index(request):
    articles = Article.objects.all().order_by('-created')
    return render(request, 'articles/index.html', {'articles': articles})

def detail(request, id):
    article = get_object_or_404(Article, pk=id)
    return render(request, 'articles/detail.html', {'article' : article})


@login_required
def create(request):
    if request.method == 'POST':
        # Request the POST and FILES data
        # POST: title, content
        # FILES: image
        form = ArticleForm(request.POST, request.FILES)

        # If form is valid save the data
        if form.is_valid():

            # Get the data from the form without saving
            article = form.save(commit=False)

            # Assing the article to the logged in user
            article.user = request.user

            # Save the data
            article.save()

            # Show sucess message
            messages.success(request, "Artcile Created !!")

            # Redirect the user to home
            return redirect('articles:index')

        # If the form is not valid show an error message
        else:
            messages.error(request, "Error when creating the article :(")

    else:
        form = ArticleForm()

    context = {
        'form': form
    }

    return render(request, 'articles/create.html', context)


@login_required
def update(request, id):
    # Get the article to update
    article = get_object_or_404(Article, pk=id)

    # Check if the logged in user
    # is the owner of the article
    if article.user != request.user:
        messages.warning(request, "You're not the owner of this item")
        return redirect('articles:index')

    if request.method == 'POST':
        # Request the POST and FILES data
        # POST: title, content
        # FILES: image
        form = ArticleForm(request.POST, request.FILES, instance=article)

        # If form is valid save the data
        if form.is_valid():

            # Get the data from the form without saving
            form.save()

            # Show sucess message
            messages.success(request, "Artcile Updated !!")

            # Redirect the user to home
            return redirect('articles:index')

        # If the form is not valid show an error message
        else:
            messages.error(request, "Error when creating the article :(")

    else:
        form = ArticleForm(instance=article)

    context = {
        'form': form,
        'article': article
    }

    return render(request, 'articles/update.html', context)


@login_required
def delete(request, id):
    article = get_object_or_404(Article, pk=id)

    # Check if the logged in user
    # is the owner of the article
    if article.user != request.user:
        messages.warning(request, "You're not the owner of this item")
        return redirect('articles:index')

    article.delete()
    messages.warning(request, "Article deleted")
    return redirect('articles:index')

users/views.py
from django.contrib import auth
from django.shortcuts import render, redirect
from django.contrib import messages

# Create your views here.
from .models import User
from .forms import LoginForm, RegisterForm


def login(request):

    form = LoginForm()
    context = {
        'form': form
    }

    if request.method == 'POST':

        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            messages.success(request, 'Welcome back ' + str(username))
            # Redirect to a success page.
            return redirect('articles:index')
        else:
            # Return an 'invalid login' error message.
            messages.warning(request, 'This user does not exist')
            return render(request, 'users/login.html', context)
    else:
        return render(request, 'users/login.html', context)


def register(request):
    if request.method == 'POST':

        username = request.POST['username']
        password = request.POST['password']
        confirmed_password = request.POST['confirmed_password']

        if password != confirmed_password:
            messages.warning(request, "Wrong password !!")
            return render(request, 'users/register.html')

        user = User.objects.create(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            messages.success(request, 'Welcome to the blog ' + str(username))
            # Redirect to a success page.
            return redirect('articles:index')
        else:
            # Return an 'invalid login' error message.
            messages.warning(request, 'This user does not exist')
            return render(request, 'users/register.html')
    else:
        form = RegisterForm()
        context = {
            'form': form
        }
        return render(request, 'users/register.html', context)


def logout(request):
    auth.logout(request)
    messages.success(request, 'Bye Bye !!')
    return redirect('articles:index')

templates/articles/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags static %}


{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/create.css' %}">
{% endblock %}


{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="form-card">
                    <h3>Create article</h3>
                    <form action="{% url 'articles:create' %}" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit" class="save btn btn-default">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/articles/derail.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-10 col-sm-8 col-md-6 col-xs-offset-1 col-sm-offset-2 col-md-offset-3">
                <div class="thumbnail">
                    <div class="row user-profile">
                        <div class="col-xs-4">
                            <img src="{{ article.user.profile_image.url }}" alt="..." class="img-circle" height="40">
                            <p class="user-name">{{ article.user.username }}</p>
                        </div>
                        <div class="col-xs-8">
                            <div class="article-time">
                                <p>{{ article.created|date:"g:i a" }}</p>
                                {% if article.user == request.user %}
                                    <div class="dropdown">
                                        <button class="btn btn-default dropdown-toggle" type="button"
                                                id="dropdownMenu1"
                                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                            <i class="fa fa-pencil" aria-hidden="true"></i>
                                        </button>

                                        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">

                                            <li><a href="{% url 'articles:update' article.id %}">Update</a></li>
                                            <li><a href="{% url 'articles:delete' article.id %}">Delete</a></li>

                                        </ul>

                                    </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    {% if article.image %}
                        <img src="{{ article.image.url }}" alt="{{ article.title }}">
                    {% endif %}
                    <div class="caption">
                        <h3>{{ article.title }}</h3>
                        <p>{{ article.content}}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/articles/index.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">

            {% for article in articles %}
                <div class="col-xs-10 col-sm-8 col-md-8 col-xs-offset-1 col-sm-offset-2 col-md-offset-2">
                    <div class="thumbnail">
                        <div class="row user-profile">
                            <div class="col-xs-4">
                                <!-- <img src="{{ article.user.profile_image.url }}" alt="..." class="img-circle"
                                     height="40"> -->
                                <p class="user-name">{{ article.user.username }}</p>
                            </div>
                            <div class="col-xs-8">
                                <div class="article-time">
                                    <p>{{ article.created|date:"g:i a" }}</p>
                                    {% if article.user == request.user %}
                                        <div class="dropdown">
                                            <button class="btn btn-default dropdown-toggle" type="button"
                                                    id="dropdownMenu1"
                                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                                <i class="fa fa-pencil" aria-hidden="true"></i>
                                            </button>

                                            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">

                                                <li><a href="{% url 'articles:update' article.id %}">Update</a></li>
                                                <li><a href="{% url 'articles:delete' article.id %}">Delete</a></li>

                                            </ul>

                                        </div>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        {% if article.image %}
                            <img src="{{ article.image.url }}" alt="{{ article.title }}">
                        {% endif %}
                        <div class="caption">
                            <h3><a href="{% url 'articles:detail' article.id %}">{{ article.title }}</a></h3>
                            <p>{{ article.content|truncatechars:140 }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/articles/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags static %}


{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/create.css' %}">
{% endblock %}


{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <div class="form-card">
                    <h3>Create article</h3>
                    <form action="{% url 'articles:update' article.id %}" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit" class="save btn btn-default">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">

    {% block css %}
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% endblock %}

    <title>Medium Blog</title>
</head>

<body>

{% include 'navbar.html' %}


<div id="content">

    <div class="row">
        <div class="col-xs-10 col-sm-8 col-md-6 col-xs-offset-1 col-sm-offset-2 col-md-offset-3">
            {# Django Messages #}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endfor %}
        </div>
    </div>

    <div class="container">
            {% block content %} {% endblock %}
    </div>
    
</div>

{% block javascript %}
    <script
            src="https://code.jquery.com/jquery-3.1.1.min.js"
            integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
            crossorigin="anonymous"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


    <script>
        // Remove the Django message after 5 seconds
        setTimeout(function () {
            let $target = $('.alert');
            $target.hide('slow', function () {
                $target.remove();
            });
        }, 5000);
    </script>
{% endblock %}

</body>

</html>

templates/navbar.html
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand logo" href="{% url 'articles:index' %}">Fikra</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">

                {% if request.user.is_authenticated %}
                    <li><a href="{% url 'articles:create' %}">Create Article</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">{{ request.user }} <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'users:logout' %}">Logout</a></li>
                        </ul>
                    </li>

                {% else %}

                    <li><a href="{% url 'users:login' %}">Sign in</a></li>
                    <li><a href="{% url 'users:register' %}">Sign up</a></li>


                {% endif %}


            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

templates/users/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags static %}


{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/create.css' %}">
{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-md-6 col-md-offset-3">
                <div class="form-card">
                    <form action="{% url 'users:login' %}" method="POST">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button class="btn btn-primary" type="submit">Login</button>
                    </form>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

templates/users/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags static %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/create.css' %}">
{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-md-6 col-md-offset-3">
                <div class="form-card">
                    <form action="{% url 'users:register' %}" method="POST">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button class="btn btn-primary" type="submit">Create Account</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}